### ISSUE TITLE
#Resizing Issue

### ISSUE THREAD

**Issue by BhardwajJatin2109** [JivanshM/scm_project#5]
While resizing the site, bottom left div does not occupy full section and lack of responsiveness in text of ( Podcast and Shows) on left side.
![image](https://github.com/JivanshM/scm_project/assets/156661099/88280a62-d091-46bc-9cc9-b024d16513f0)

**Comment by BhardwajJatin2109** [comment]
![img](https://github.com/JivanshM/scm_project/assets/156661099/2ee403cf-3d84-4635-bcf9-f169ed8907ac)

**Comment by JivanshM** [comment]
Updated project to address layout issues and improve responsiveness for better user experience.

**Comment by JivanshM** [comment]
Updated project to address layout issues and improve responsiveness for better user experience.
